theme = "catppuccin_mocha_transparent"

[editor]
line-number = "relative"
insert-final-newline = true
color-modes = true

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
nbsp = "all"
nnbsp = "all"
